name: 'Publish to GitHub Pages'

permissions:
  contents: write

env:
  GODOT_VERSION: 3.5.1

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    container:
      image: barichello/godot-ci:3.5.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move HTML5 templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Create staging directory
        run: mkdir -v -p docs

      - name: Build
        run: godot -v --export "HTML5" ../docs/index.html src/project.godot

      - run: git config --global --add safe.directory '*'

      - name: Commit docs
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Update gh pages'
          add: '.'